package com.example.culturecompass


val description1 = "India is home to over a billion people, accommodating incredible cultural fullfilled diversity between languages, geographic regions, religious and traditions and social stratifications. In recognition of this large demographic diversity." +
        "\n\nthe following descriptions are not intended to represent every Indian person. However, there are common themes and principles that contribute to the values, attitudes, beliefs and norms of the dominant society. \n" +
        "\n" +
        "Geography and Space\n" +
        "\n" +
        "India’s geography and climate is incredibly diverse. Northern India is characterised by the snowy mountain range of the Himalayas and the Great Indian (Thar) Desert. Meanwhile, tropical jungles, rainforests, coastal plains, islands and beaches distinguish the south. Nature plays a vital role in India. \n\nEspecially rivers such as the Ganga (or ‘Ganges’) in the north and Godavari in the central and southeast. Both provide irrigation for farmlands, a method of transportation and are considered sacred to many followers of Hinduism.\n" +
        "\n" +
        "Ethnic and Linguistic Composition\n" +
        "\n" +
        "Although India does not officially recognise racial or ethnic categories in the national census, it continues to be one of the most ethnically diverse populations in the world. Broadly, the ethnicities of India can be broken down into main groups on the basis of their linguistic backgrounds, the two largest being Indo-Aryan and Dravidian.\n" +
        "\nFor example, many people belonging to Indo-Aryan ethnicities live in the northern half of the country. Indo-Aryan languages commonly spoken include Hindi, Gujarati, Bengali, Marathi, Urdu, Odia and Punjabi. Meanwhile, people belonging to Dravidian ethnicities generally live in the southern half of the country. \n" +
        "\n" +
        "Dravidian languages commonly spoken include Tamil, Kannada, Telugu and Malayalam. These labels of ‘Indo-Aryan’ and ‘Dravidian’ usually serve as a helpful way to categorise the origins of Indian ethnic diversity, although they don’t necessarily reflect people’s personal identity. For example, people are unlikely to describe themselves as ‘Indo-Aryan’ or ‘Dravidian’.\n" +
        "\n" +
        "Within these broad language groups, there is vast linguistic diversity accounting for 22 major languages and hundreds of regional or local languages. Most Indians tend to be bilingual or multilingual, speaking an official language along with their regional language(s). English is considered to be a subsidiary official language that is often reserved for governmental and commercial purposes. \n" +
        "\n" +
        "\n" +
        "National Identity\n" +
        "\n" +
        "The ‘Indian identity’ has evolved continuously over the country’s history as political and religious institutions have changed within and outside of India. For example, the British Raj (1858-1947) brought about vast changes in the country’s economic, political and cultural spheres. India’s independence from the British in 1947 was accompanied by the partition of India. \n\nPakistan into the Republic of India and the Islamic Republic of Pakistan respectively. This led to mass violence that continues to be a source of trauma and sadness for many Muslims, Sikhs and Hindus that reside in the Punjab region in northwestern India.\n" +
        "\n" +
        "Partition reflects the complexities in Indian identity with respect to religion. One temptation is to correlate Hindu identity and values with the Indian national identity. This correlation has been made since British colonisation. However,present the religious and cultural diversity of India. \n\nWhile it may seem like a useful device for describing a unified national identity, such generalisations perpetuate significant tensions among various groups in Indian society.\n" +
        "\n" +
        "Social Structure and Stratification\n" +
        "\n" +
        "India has a highly stratified traditional social structure, often referred to as the ‘caste’ system. The term ‘caste’ comes from the word ‘casta’, which was used by Portuguese observers to describe the social stratification of Indian society. \n\nThe caste system is an ancient institution that is generally believed to be unique to the Indian subcontinent. Although often classified under one term, the caste system actually represents two different overlapping systems of stratification.\n" +
        "\n" +
        "Karma, Acceptance and Personal Choice\n" +
        "\n" +
        "Many Indians tend to have a sense of acceptance towards one’s life position or a belief that, due to actions in one’s past life, good or bad personal circumstances are deserved. This attitude partly stems from religious ideas such as ‘karma’ (the idea that one’s actions will affect their current or future life) and ‘samsara’ (the cycle of rebirth).\n" +
        "\nThe interplay of these social, cultural and religious factors allows people to be accepting of life events and trajectories. However, this is not to be interpreted as Indians being unwilling to take responsibility for life circumstances. Many often contemplate how their actions may impact their future and make decisions accordingly. \n" +
        "\nAdaptability and Light-Heartedness\n" +
        "\n" +
        "The large population size of India has not led average Indians to think of themselves as ‘one among many’ and certainly has not diminished their aspirations. Instead, diversity is celebrated alongside an inventive and entrepreneurial spirit. In this sense, many Indians are very adaptive and creative, often visualising big possibilities for themselves, their people and country.\n" +
        "\n"

val description2 = "This magnificent capital of Persia from 1598 to 1722 is now the third largest city in Iran. Isfahan is considered one of the most beautiful cities in the world. As well as its many gorgeous boulevards, astonishing Persian-Islamic architecture, palaces, mosques and minarets, Isfahan is home to one of the largest and most impressive city squares, the Iman Square. This city is more than just beautiful, however, as it is home to wide range of impressive architecture and historical monuments. The bridges over the river are particular gems. \n" +
        "The oldest of these is the Shahrestan Bridge, whose foundations were built between the third to seventh centuries and it is a prime example of Sasanian architectural style. Further sites include the 17th-century Imam Mosque, which is viewed as a masterpiece of Persian architecture for its stunning mosaic tiles with calligraphic inscriptions in seven different colors. Meanwhile, the Ali Qapu is an early 17th-century, seven-story royal residence with stunning wall paintings. Isfahan is also the home to several important art institutions, including the Museum of Contemporary Art and the Natural History Museum of Isfahan, housed in a 15th-century, Timurid era building.\n"

val description3="Founded in 331 BC by Alexander the Great, Alexandria was second only to Rome in terms of power in the ancient world. But it was also an important center for learning. It was home to the Royal Library of Alexandria – one of the most important and largest libraries in the ancient world – and many of the most celebrated scholars of the ancient world studied here. The exact occasion when the library burnt down is disputed, but its destruction is widely viewed as a tragic loss of cultural knowledge.\n"+
"Modern Alexandria may not be able to rival this almost mythic status that has been ascribed to the city in ancient times, but the city has had an important role in modern literature. The Alexandria-born Greek poet Constantine P. Cavafy (1863-1933) was instrumental in the revival of Greek poetry, and expatriate British writer Lawrence Durrell wrote his most famous work The Alexandria Quartet while living in the city."

val description4="Samarkand in Uzbekistan is described by UNESCO as ‘a masterpiece of Islamic cultural creativity’ and a crossroads of world cultures for over two millennia. Samarkand is dominated calligraphic inscriptions in seven different colors. Meanwhile, the Ali Qapu is an early 17th-century, seven-story royal residence with stunning wall paintings. Isfahan is also by the Old Town of the 14th and 15th centuries, which comprises a series of mosques, madrassahs, and mausoleums.\n"+ "Together they form the highest artistic and architectural achievement of Central Asia. was advanced both economically and administratively. Heads of household money to build infrastructure and provide food and security to the people in times of need. It was also, astronomy, and calendar systems. Many ruins are located just outside of the modern city centre, which also offers plenty to do and see.The houses are filled with interior decoration and courtyards, with notable sites being the Bibi-Khanum Mosque, the Registan and the Ulugh-Beg Observatory."

val description5="A city located high in the Andes Mountains, Cusco was once the capital of the legendary Incan Empire. Not much is known about the city’s origins, but it is believed that it was built in the image of the puma, an animal sacred to the Incas. Either way, it is clear that the city was constructed in adherence to distinct urban planning. \n"+ "Cusco was advanced both economically and administratively. Heads of household were expected to pay taxes, and city officials used the money to build infrastructure and provide food and security to the people in times of need. It was also a hub for mathematics, astronomy, and calendar systems. Many ruins are located just outside of the modern city centre, which also offers plenty to do and see."

val description6="No doubt, Athens has played a fundamental role in shaping the Western world into what it is today. By 1400 BC the city was already prominent in the ancient world. It has been inhabited for over 7000 years. A city-state of the once-burgeoning ancient Greece, Athens played a critical role in shaping philosophy, drama, literature, and science. Its central location made it a hotbed for cultural interchange and commerce. Athens is home to many awe-inspiring ruins like the Parthenon and The Temple of Olympian Zeus. Athens still serves as a bustling metropolis and is known for its culture, arts, media, entertainment, commerce, and finance."

val description7="One of the most historically preserved cities in Europe, Prague offers a perspective of life in the middle ages. Some famous figures from Prague include the artist Alphonse Mucha (although born in Ivančice), and author Franz Kafka. Mozart was also a frequent visitor here.The Bohemian city is rich in folklore; it was home to a historically large Jewish community, and had a significant monastic presence. \n In Prague you can also find the oldest functioning astronomical clock, the Prague Castle, and the tavern where Pilsner beer was first produced.It was part of the Austro-Hungarian Empire and more recently, a member of the Soviet Bloc. Since the Czech Republic gained its independence, Prague has become an increasingly chic city with a multicultural presence, great commercial centers, and acclaimed eateries."

val description8="Boston is one of the oldest cities in the United States. Historically, it is home to America’s intellectual elite. In fact, the nation’s first university, Harvard, was founded here. Today it is still the city with the most colleges in the country.In a political sense, Boston was a significant site for the American Revolution, making it the backdrop to many events that have altered the course of history. The city has maintained much of its historic urban layout. \n The city’s New England-style architecture and cobblestoned streets still pay homage to those times. Boston has become much more than its past, as it has become an innovative and modern city with a dynamic culture."
val description9="Beijing is officially more than 3000 years old, but it has played a role in Chinese history for as long as eight millennia, as it is one of the four ancient capitals of China. Specifically, Beijing was the home base of the notorious Ming and Qing Dynasties, as well as the capital under Chairman Mao during the Chinese Communist Revolution. \nThe city is ripe for exploring all that they left behind.There is the famed Forbidden City, which was the astounding imperial palace under the Qing Dynasty. There are also many exquisite Chinese Temples, and you can walk a good portion of the Great Wall. Beijing bears an expansive history of one of the greatest and most fascinating human civilizations, and it has since become highly modernized."
val description10="Berlin is known to strike the perfect balance between poor and sexy. Yet, its story is one that requires some reading between the lines, as you explore the city at present. Berlin’s history is something you feel more than you see, as you get lost in its hip, nonchalant mood, and suddenly find yourself getting goose bumps as you recall everything that’s happened here. \n Berlin was the capital of Nazi Germany. and it was infamously divided down the middle during the Cold War. Before this, it was graced by the likes of Marx, Einstein, and many other great thinkers. Its very essence was born out of this history as its inhabitants developed the counterculture and nightlife, which makes it so famous today, in response to its rich (albeit sometimes tumultuous) past."
val description11="Istanbul is the crown jewel in an important thread of history. When it was known as Constantinople, it was the capital of the Byzantine Empire following the fall of Rome, and it was a significant stop in the Silk Roads. In fact, due to its central location between the East and the West, most classical civilizations played some part in shaping it. Istanbul was also an Ottoman capital until it was dissolved after World War I. \n Reminders of each element of its rich history can be witnessed throughout the city, because much of it is marvellously preserved. A great example is the Hagia Sophia, which was a massive church under the Byzantine Empire that was converted into a mosque during the Ottoman rule."
val description12="It is believed that the Phoenician Queen Dido founded Carthage around 900 BC. The Romans ultimately brought the Carthaginian Empire to ruin as a result of the Punic Wars. Because of its central location, however, they realized that is was a necessary strategic location in their empire. Under Julius Caesar, the city was revived and ultimately flourished as a colony.  \n Unfortunately, Carthage’s plight as a foreign conquest did not end there. The Vandals, Muslim Conquerors, and the Byzantines all had their hand in Carthage’s history. Many ruins were left behind including Roman villas, the ancient Antoine Baths, the Sanctuary of Tophet, and the Punic Port that still harbours remarkable views of the sea."
val description13="Dating all the way back to 11th century BC, Varanasi is one of the oldest cities in the world. It is located in the Indian state of Uttar Pradesh on the River Ganges, and many come to its banks to perform funeral rites, as it is believed those who die here will be granted eternal life.Varanasi is also home to many temples, making it one of Hinduism’s seven holy cities. One of its most notorious sites is the Golden Temple, which honours the Hindu god Shiva.Nowadays the bustling Varanasi is as vibrant and colourful as ever. Visit to experience the moving rites of life and death taking place at the riverbank, and get lost in one of the city’s many ancient labyrinthine passageways."
val description14="Florence is the birthplace of the Renaissance, home to poets like Dante, Boccaccio and Petrarch, and once ruled by the Medici family, the patrons of Michelangelo, da Vinci and Botticelli. There is breathtaking architecture aplenty to enjoy like the Campanile of Giotto and the iconic Duomo of Brunelleschi, and then some of the finest galleries in the world to explore.  \n The collections of the Uffizi and the Petti Palace show off many works of the Florentine School of painters like Donatello, Fra Angelico and Botticelli amongst others, while in the Accademia Gallery, you’ll find Michelangelo’s David."
val description15="If Paris is the City of Art, then Vienna is the City of Music. And it’s the city of Freud where the science of psychoanalysis was born that underpinned so much modernist art and literature. Vienna has been home to Mozart, Mahler, Beethoven and Johan Strauss II. There are concerts everywhere. \n In the parks, in churches like Stephansdom, and in fine venues like the Staatsoper and the Wiener Konzerthaus. The Museums quartier is a major cultural district too, where you’ll find the Leopold Museum and the Kunsthistorisches Museum that’s full of works by Old Masters. Vienna is famed too for its Art Nouveau buildings, especially those by Otto Wagner."
val description16="Not only is Jerusalem one of the oldest cities in the world, it is also central to the religions of Judaism, Islam and Christianity. According to Jewish tradition, King David conquered the city in around 1000 BC and made it the capital of the Kingdom of Israel. For Christians it is the site of Jesus’ crucifixion and for Muslims it is where the prophet Muhammad ascended from into heaven. Unsurprisingly, Jerusalem’s Old City is home to numerous important holy sites, including the Western Wall – the remains of the great Jewish temple destroyed by the Romans 2000 years ago.  \n The Church of the Holy Sepulchre, and the Dome on the Rock. But Jerusalem hasn’t only made it to our list of the most cultural cities in the world because of its religious sites. The Israel Museum holds an extensive collection of Israeli and European art; the Rockefeller Museum has an impressive archaeological collection; and the Yad Vashem Holocaust Memorial Museum is home to the largest library of Holocaust-related information, holding approximately 100,000 books and articles, and commemorates the murder of 1.5 million Jewish children by the Nazis."
val description17="Granada in Andalusia, Spain has a unique culture, a reflection of its Moorish past. Granada is the city of Lorca, the greatest of Spanish poets, and you can see the ancient Arch of Elvira referenced in his work. There’s lots of flamenco played here too – in bars and restaurants and a festival is held in the caves of the Sacramenta district. Granada’s main event is the magnificent Islamic architecture of the Alhambra built by the emirs of Al-Andalus, which is now a UNESCO World Heritage Site."
val description18="Walking around Rome you can admire the classical ruins and the masterpieces of the Renaissance and Baroque eras built by the popes. The palazzos, piazzas, churches and fountains are by master architects like Michelangelo, Bernini and Borromini. The Vatican Museums are unmissable and culminate in the Sistine Chapel. For film aficionados, Rome was the home city of the director Fellini and the setting for ‘La Dolce Vita,’ one of the classics of European cinema."
val description19="There’s something to suit everyone in London. Literary sites like Baker Street and Keats’ House in Hampstead are worth seeing. Then for fans of the performing arts, the English National Opera, the West End theatres, and the London Symphony Orchestra at the Barbican are great places to explore. For more contemporary acts, have a look at what’s on at Earl’s Court, Brixton Academy or the O2 Arena. Finally, art lovers are handsomely catered for with the British Museum, National Gallery, Royal Academy, Tate Britain, Tate Modern and the Saatchi Gallery."
val description20="There are more national museums in Shanghai – 27 in total – than anywhere in the world. Then there are the iconic landmarks like The Bund on the Huangpu and the Yuyuan Gardens, and those museums. Two of the best are the China Art Museum and the Shanghai Museum that’s full of ancient bronzes, ceramics, and calligraphy."
